server:
  port: 8080
  context-path: /

spring:
  jpa.hibernate.ddl-auto: create-drop
  datasource.url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mentoring
  datasource.username: user_mentoring
  datasource.password: passmentoring