server:
  port: 8080
  servlet:
    application-display-name: mentoring
    context-path: /mentoring

spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mentoring
    username: user_mentoring
    password: passmentoring